### ISSUE TITLE
Update Manage Command 'Selected Event' Display 

### ISSUE THREAD

**Issue by sharan8** [CS2103-AY1819S1-W16-2/main#110]
Current UI:
> 
> ![image](https://user-images.githubusercontent.com/15187989/46968841-e3573980-d0e6-11e8-9553-76fcb05393ce.png)

A suggestion: For 'Selected Event To Manage: 1', could we include the event name as well? For example - 'Selected Event To Manage: Blood Donation Drive 2018 [1]'. Just the index seemed a little misleading at first.

**Comment by iMarbles** [comment]
UI Updated to as follows:

![image](https://user-images.githubusercontent.com/15187989/47962099-26eff400-e052-11e8-950e-ae17d890a415.png)
