### ISSUE TITLE
DeveloperGuide.adoc: Export volunteer certificate

### ISSUE THREAD

**Issue by iMarbles** [CS2103-AY1819S1-W16-2/main#126]
Minor thoughts:
* Is it possible to add a border around the sample cert? The white blends into the background of the documentation. Makes it uneasy on the eyes.

* If the feature is not available yet, please add [Coming in V1.3] next to the feature name.

* Might want to display alternatives with pros and cons in a table instead.

**Comment by sharan8** [comment]
Done 👍
