### ISSUE TITLE
Update README.adoc

### ISSUE THREAD

**Issue by iMarbles** [CS2103-AY1819S1-W16-2/main#44]
1. Add a UI mockup of your intended final product.

2. Note that the image of the UI should be docs/images/Ui.png so that it can be downloaded by our scripts.

3. The original README.adoc file (which doubles as the landing page of your project website) is written to read like the introduction to an SE learning/teaching resource. You should restructure this page to look like the home page of a real product (not a school project) targeting real users  e.g. remove references to addressbook-level3, Learning Outcomes etc. mention target users, add a marketing blurb etc. On a related note, also remove Learning Outcomes link and related pages.

4. Acknowledge the original source of the code i.e. AddressBook-Level4 project created by SE-EDU initiative at https://github.com/se-edu/

**Comment by Kratious** [comment]
Updated README to reflect morphed idea and badges for this repository.
