### ISSUE TITLE
Update UserGuide.adoc for CS2101

### ISSUE THREAD

**Issue by iMarbles** [CS2103-AY1819S1-W16-2/main#74]
1. Quick Start:
* Do not number the steps without a Lead-in.
* Ensure you have Java version 9.... (Change this to CHECK that you have.... -Action word)
* Diagram/Figures should have captions.
* Number 6 is not an instruction. It is extra information. Do not number (Some example commands you can try....) 
* Number 7 is not part of quick start. Write it separately.

2. Features:
* Keep the box which provides extra information.
* Fix inconsistencies in the features. Have to explain what the command does (even if it is common sense)
* After showing the example, might want to provide a diagram to show what happens after entering the command. Before-After diagram would be helpful.

3. Command Summary:
* Might want to present in a table? Enhance ease of use for user guide. 

4. Other notes:
* Ensure that everything is written in good English
* Introduction section is important

**Comment by sharan8** [comment]
**Command Format:**
1. Subheading - Sentence case 
2. Box up the command in gray (executables) - end of subheading, after semicolon
3. Description of command
4. Format of how to input the command (input in gray box as well)
5. Additional information in a 'information' box
