### ISSUE TITLE
Update Developer Guide for CS2101

### ISSUE THREAD

**Issue by iMarbles** [CS2103-AY1819S1-W16-2/main#75]
1. Table of Content:
* Fix sentence case for consistency. 
First level: Title Case
Eg. Title Case of Project (of: grammatical word)
Second level: Sentence case
Eg. UI component. (Second word is lower case)

2. Introduction:
* This section is missing from the current DG!
* Describe the software.
* Describe the purpose of the DG, who its intended audience is and perhaps how to use it.
* Provides a preview of the contents of the DG.
* May even include some info about the developer team, and how to contact them.

3. Setting up:
* Same problem as UG. Need a lead in before numbering the steps. 
* Use bullets if order is not important. 
* Always end with colon for a lead in sentence. Colon is used to introduce list of steps or items.
* Always end with a full stop after every instruction.
* 1.4.1 Configuring the code style: TO RECTIFY (End with colon, not a comma)
* Have to rewrite for consistency.

4. Design:
* 2.1 Architecture:
-- Come up with a numbering system and standardize. 
-- Decide between title case or sentence case for the caption.
-- All diagrams needs to come with a explanation.
-- The architecture diagram given above.... Given below is a quick overview of each component. (Fix the second half of the sentence): How many components are there?
-- Main has only.... It is responsible for, (INITIALIZING)
-- Rest of the App consists of four components. How are the 4 other components different from Main and Commons?
-- Inconsistent description of the components.
-- Figure 2. See the FIGURE below. Not diagram!
-- Is Events-Driven nature of the design a header? Why is it not numbered? What is it doing there?

* 2.2 UI component:
-- Have a diagram but there is no reference to it. 
-- If the text below has a connection to the diagram, have to highlight the reference.

* 2.3 Logic component:
-- Figure, caption, set of numbers(?). What are the numbers about?
-- Have to rewrite the whole section.

* 2.4 Model component:
-- No consistency in style. Suddenly show bullets.
-- Missing captions for diagrams.

* 2.5 ???:
-- Same issues as above

* 2.6: Common classes:
-- Conflict with the commons earlier on? Why is this separate?
-- Is this section necessary?

5. Implementation:
* Everyone to write their own parts. Explain the functions you have added to the software. 
* Have to be consistent with everyone.
* Mind the language (Design considerations: User verbs as the alternative. Saves vs Save. Individual commands...? Drop the WE) 
* Check the language (Subject-verb agreement)
* Notice the different kinds of diagrams. Illustrations do not need captions. 
* Sequence diagram for the Undo/Redo function needs to have a caption. The figure below shows....
* Logging levels contains inconsistency in language.

6. Testing:
* Explain the need for testing. (Write a preface)

7. Dev Ops:
* See if there is a need to update

8. Appendices:
* Same as 6.

**Comment by sharan8** [comment]
**Task Allocation:**
Sharan: 
- Table of Contents
- Introduction

Afiq: 
- Setting up

Amabel & Jing Han
- Design

Wen Jun 
- Testing
- Dev Ops
- Appendices

**Comment by sharan8** [comment]
**Style Conventions:**
- All images should be labelled as Figures
- For headers in bold, all beginning of words to be capitalized
- For subheaders, follow sentence case
- All images to be labelled as Figures
- Use powerpoint to come up with your sequence diagrams

**Comment by iMarbles** [comment]
* Each figure to use sentence case

**Comment by iMarbles** [comment]
> **Style Conventions:**
> 
> * All images should be labelled as Figures
> * For headers in bold, all beginning of words to be capitalized
> * For subheaders, follow sentence case
> * All images to be labelled as Figures
> * Use powerpoint to come up with your sequence diagrams

* Each figure caption to use sentence case
